name: Deploy to Server

on:
  push:
    branches:
      - main   # Adjust this branch as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24'   # Update as needed

    - name: Build Application
      run: |
        go build -o learning-management .

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Ensure the destination directory exists.
          mkdir -p ${{ secrets.DEST_PATH }}
          
          # Copy the new binary.
          cp learning-management ${{ secrets.DEST_PATH }}/learning-management
          
          # Copy templates directory if needed.
          cp -r templates ${{ secrets.DEST_PATH }}/templates
          
          # Copy static files if you have any.
          cp -r static ${{ secrets.DEST_PATH }}/static
          
          # Restart the application service.
          ${{ secrets.RESTART_SCRIPT }}
